# Generated by Django 5.1 on 2024-09-26 08:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Rating between 1 and 10', null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('MAR', 'Marketing'), ('FIN', 'Finance'), ('SAL', 'Sales')], max_length=4, null=True)),
                ('job_position', models.CharField(max_length=255)),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('role', models.CharField(choices=[('EMP', 'Employee'), ('MNG', 'Manager'), ('ADM', 'Admin')], max_length=4, null=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.performance')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('job_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.jobdetails')),
            ],
        ),
    ]
